language: ruby
sudo: false

ruby_supported_versions:
  - &ruby_2_1 2.1.10
  - &ruby_2_2 2.2.10
  - &ruby_2_3 2.3.8
  - &ruby_2_4 2.4.6
  - &ruby_2_5 2.5.5
  - &ruby_2_6 2.6.3
  - &ruby_head ruby-head

rails_supported_versions:
  - &rails_4_1 RAILS_VERSION=4.1
  - &rails_4_2 RAILS_VERSION=4.2
  - &rails_5_0 RAILS_VERSION=5.0
  - &rails_5_1 RAILS_VERSION=5.1
  - &rails_5_2 RAILS_VERSION=5.2
  - &rails_6_0_0 RAILS_VERSION=6.0.0
  - &rails_master RAILS_VERSION=master

cache:
  directories:
    - vendor/bundle

before_install:
  - "travis_retry gem update --system 2.7.9"
  - "travis_retry gem install bundler -v '1.17.3'"
install: BUNDLER_VERSION=1.17.3 bundle install --path=vendor/bundle --retry=3 --jobs=3

script:
  - bundle exec rake ci
after_success:
  - codeclimate-test-reporter

env:
  matrix:
    - *rails_4_1
    - *rails_4_2
    - *rails_5_0
    - *rails_5_1
    - *rails_5_2
    - *rails_6_0_0
    - *rails_master

rvm:
  - *ruby_2_1
  - *ruby_2_2
  - *ruby_2_3
  - *ruby_2_4
  - *ruby_2_5
  - *ruby_2_6
  - *ruby_head


matrix:
  include:
    - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=4.1 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
    - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=4.2 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
    - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=5.1 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
    # See JRuby currently failing on Rails 5+ https://github.com/jruby/activerecord-jdbc-adapter/issues/708
    # - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=5.0 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
    # - { rvm: jruby-head,     jdk: oraclejdk8, env: "RAILS_VERSION=5.1 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
  exclude:
    - { rvm: *ruby_2_1,  env: *rails_5_0 }
    - { rvm: *ruby_2_1,  env: *rails_5_1 }
    - { rvm: *ruby_2_1,  env: *rails_5_2 }

    - { rvm: *ruby_2_1,  env: *rails_6_0_0 }
    - { rvm: *ruby_2_2,  env: *rails_6_0_0 }
    - { rvm: *ruby_2_3,  env: *rails_6_0_0 }
    - { rvm: *ruby_2_4,  env: *rails_6_0_0 }

    - { rvm: *ruby_2_1,  env: *rails_master }
    - { rvm: *ruby_2_2,  env: *rails_master }
    - { rvm: *ruby_2_3,  env: *rails_master }
    - { rvm: *ruby_2_4,  env: *rails_master }

  allow_failures:
    - { rvm: *ruby_2_4,  env: *rails_4_1 }
    - { rvm: *ruby_2_5,  env: *rails_4_1 }
    - { rvm: *ruby_2_6,  env: *rails_4_1 }

    # allow RAILS_VERSION=master to fail against ruby 2.5+ until this gem supports RAILS_VERSION
    # https://github.com/rails/rails/blob/master/RAILS_VERSION
    # https://github.com/rails-api/active_model_serializers/blob/0-10-stable/active_model_serializers.gemspec#L24
    - { rvm: *ruby_2_5,  env: *rails_master }
    - { rvm: *ruby_2_6,  env: *rails_master }

    - rvm: *ruby_head
    # - { rvm: *ruby_head, env: *rails_4_1 }
    # - { rvm: *ruby_head, env: *rails_4_2 }
    # - { rvm: *ruby_head, env: *rails_5_0 }
    # - { rvm: *ruby_head, env: *rails_5_1 }
    # - { rvm: *ruby_head, env: *rails_5_2 }
    # - { rvm: *ruby_head, env: *rails_6_0_0 }
    # - { rvm: *ruby_head, env: *rails_master }

    - rvm: jruby-head
    # See JRuby currently failing on Rails 5+ https://github.com/jruby/activerecord-jdbc-adapter/issues/708
    - { rvm: jruby-9.1.13.0, jdk: oraclejdk8, env: "RAILS_VERSION=5.1 JRUBY_OPTS='--dev -J-Xmx1024M --debug'" }
  fast_finish: true
